### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by mikelehu**
I have made the following changes:

- We have defined correctly no-common solver options ( avoiding  warnings) 
- Some improvements in the stop criteria of fixed-point iteration
- We have restructured the code to improve performance (we have separated sequential and parallel code).

Soon, we will add the IRKGL-simd implementation to IRKGaussLegendre.jl for double floating point calculations

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
The format check failure is the thing I was mentioning before about running JuliaFormatter.

**Comment by mikelehu** [comment]
To solve the "format check problem" of the pull request "improvements #35" I have done the following:
1-  JuliaFormatter
julia>using JuliaFormatter
julia>format_file(“IRKGLSolver.jl”)
2- commit and push the changes
3- create a new pull request.

**Comment by ChrisRackauckas** [comment]
It's usually best to just run `format` on the directory of the repo and it'll do all files.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLStyle#juliaformatter has a copy-paste solution.

**Pull request closed without merging**
