### PR TITLE
Improvements 2022-08

### PR DESCRIPTION
**Pull request by mikelehu**
I have made the following changes:

- We have defined correctly no-common solver options ( avoiding  warnings) 
- Some improvements in the stop criteria of fixed-point iteration
- We have restructured the code to improve performance (we have separated sequential and parallel code).

Soon, we will add the IRKGL-simd implementation to IRKGaussLegendre.jl for double floating point calculations

### CODE REVIEW

**Comment by mikelehu** [comment]
The format check failure continues, but I now understand that the "format" of the eight files is correct because JuliaFormatter returns
true:

`
julia> format_file("IRKCoefficients.jl")
true

julia> format_file("IRKGaussLegendre.jl")
true

julia> format_file("IRKGL16AuxFunctions.jl")
true

julia> format_file("IRKGL16Solver.jl")
true

julia> format_file("IRKGL16step_adaptive_par.jl")
true

julia> format_file("IRKGL16step_adaptive_seq.jl")
true

julia> format_file("IRKGL16step_adaptive_par.jl")
true

julia> format_file("IRKGL16step_fixed_par.jl")
true

julia> format_file("IRKGL16step_fixed_seq.jl")
true

`

**Comment by mikelehu** [comment]
The format check failure continues, but I now understand that the "format" of the eight files is correct because JuliaFormatter returns true:

julia> format_file("IRKCoefficients.jl")
true

julia> format_file("IRKGaussLegendre.jl")
true

julia> format_file("IRKGL16AuxFunctions.jl")
true

julia> format_file("IRKGL16Solver.jl")
true

julia> format_file("IRKGL16step_adaptive_par.jl")
true

julia> format_file("IRKGL16step_adaptive_seq.jl")
true

julia> format_file("IRKGL16step_adaptive_par.jl")
true

julia> format_file("IRKGL16step_fixed_par.jl")
true

julia> format_file("IRKGL16step_fixed_seq.jl")
true

**Comment by ChrisRackauckas** [comment]
Are you not including the tests?

**Comment by ChrisRackauckas** [comment]
And if you're doing it file-by-file, are you making sure it's set to SciML style? The .JuliaFormatter.toml is only caught and used if it's done at the repo level.

**Comment by mikelehu** [comment]
#37: I had forgotten to pass JuliaFormatter to tests and ODEProblems.
#38: (next pull) I have included both (tests and ODEProblems) but  the format check failure continues,

* I am doing it file-by-file and  I have not used the sciml style explicitly.
  I will try to solve it tomorrow and thanks for everything.

**Pull request closed without merging**
