### PR TITLE
IRKGL-SIMD

### PR DESCRIPTION
**Pull request by mikelehu**
## Checklist

We include the SIMD version

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by mikelehu** [comment]
I do not understand what is wrong;  locally, the test passes

**Comment by mikelehu** [comment]
I don't know why it is failing this test:

`dts = (1 // 2) .^ (4:-1:2)
sim = test_convergence(dts, prob_ode_bigfloat2Dlinear, IRKGL16())
@test abs(sim.𝒪est[:final] - 16) < 0.5`

Any idea?

**Comment by ChrisRackauckas** [comment]
share `plot(sim)`

**Comment by mikelehu** [comment]
In the new version,

plot_sim

**Comment by mikelehu** [comment]
But in the current version,

plot_sim_

**Comment by mikelehu** [comment]
I have made a modification in "runtests.jl" :

`# dts = (1 // 2) .^ (4:-1:2)`
`dts = BigFloat.( (1 // 2) .^ (4:-1:2))      # 2024-08-7`
`sim = test_convergence(dts, prob_ode_bigfloat2Dlinear, IRKGL16())`

but the test still fails. This is now the plot(sim):

plot_sim

**Comment by ChrisRackauckas** [comment]
That is now hitting the default BigFloat accuracy limit. Use a bit larger dt's

**Comment by mikelehu** [comment]
ok, using a bit larger dts, the test passed.

`dts = BigFloat.( (1 // 2) .^ (3:-1:1))`

plot_sim

**Comment by mikelehu** [comment]
Should I be concerned about the Invalidation check?

thank you

**Comment by ChrisRackauckas** [comment]
nope, don't worry about that.

**Comment by ChrisRackauckas** [comment]
Perfect!

**Comment by ChrisRackauckas** [comment]
This needs a bit of cleaning, The data and such will make it very difficult to install the repo as the solver would always ship with all of that. Mind if I cut that out? It should go in a separate repo. I would be happy to integrate a lot of this into the SciMLBenchmarks too so it gets more visibility.

**Comment by mikelehu** [comment]
Yeah, sure, I don't mind. Organize the repository however you see fit.

**Comment by ChrisRackauckas** [comment]
Awesome. I cleaned it up in https://github.com/SciML/IRKGaussLegendre.jl/pull/71 so that it wouldn't bloat the memory in the repo. That deleted your commit history here as that's required for the full deletion, though hopefully that's okay.

**Comment by mikelehu** [comment]
Thanks Chris, I have read your comments in [71](https://github.com/SciML/IRKGaussLegendre.jl/pull/71) and I will be more careful when making pull requests in the future.

**Pull request closed without merging**
