### PR TITLE
Controls for failure

### PR DESCRIPTION
**Pull request by mikelehu**
I have made the following changes:

-  Fixed step size implementation : stop the integration when it reaches the maximum number of iterations.
-  Include meaningful error messages

### CODE REVIEW

**Comment by mikelehu** [comment]
I have troubles with this pull request, some checks were not successful. 
Could you help me?

**Comment by mikelehu** [comment]
Can this pull request be merged to the  master and be the version for new installs from now on?

**Comment by ChrisRackauckas** [comment]
Yup I gotcha. I'll release it in about half an hour.

**Comment by ChrisRackauckas** [comment]
Thanks for handling this!

**Comment by mikelehu** [comment]
Very good!
Thank you very much for your time and also,  for fixing it so quickly

**Pull request merged**
